config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "tasks" => "tasks#index"
  get "tasks/new" => "tasks#new"
  get "tasks/:id" => "tasks#show", as: :task
  post "tasks" => "tasks#create"
  get "tasks/:id/edit" => "tasks#edit", as: :edit
  patch "tasks/:id" => "tasks#update"
  delete "tasks/:id" => "tasks#destroy", as: :delete
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit the task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title, "Write a task here" %>
  <%= f.text_field :title %>
  <%= f.label :details, "Write the details of the task" %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>

<%end%>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul><% @tasks.each do |task| %>
  <li><%= link_to task.title, task_path(task) %></li>
  <li><%= task.completed %></li>
 <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title, "Write a task here" %>
  <%= f.text_field :title %>
  <%= f.label :details, "Write the details of the task" %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>

<%end%>

app/views/tasks/show.html.erb
<h1><%=@task.title %></h1>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>
<%= link_to "Back to the list", tasks_path %>
<%= link_to "Edit this task", edit_path %>
<%= link_to "Delete this task", delete_path(@task), method: :delete, data: {confirm: "Are you sure?"} %>